language: cpp

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - MATRIX_SCRIPT='./scripts/build-linux.sh'

  - os: osx
    osx_image: xcode11.3 # OS X 10.14
    env:
    - MATRIX_EVAL=""
    - MATRIX_SCRIPT='./scripts/build-mac.sh'

  - os: windows
    env:
    - MATRIX_EVAL=""
    - MATRIX_SCRIPT='./scripts/build-windows.sh'

before_install:
- eval "${MATRIX_EVAL}"

script:
- "${MATRIX_SCRIPT}"

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_API_KEY
  file_glob: true
  file:
  - dist/*
  skip_cleanup: true
  on:
    tags: true
